
Ottawa:
  type: Land
  alligence: Canada
  res: 1
  pop: 0
  muster: 1
New York:
  type: Land
  alligence: USA
  res: 2
  pop: 1
  muster: 2
Washington:
  type: Land
  alligence: USA
  res: 2
  pop: 2
  muster: 3
Irish Sea:
  type: Sea
North Atlantic Ocean:
  type: Ocean
Mid Atlantic Ocean:
  type: Ocean
South Atlantic Ocean:
  type: Ocean
Rio de Janeiro:
  type: Land
  alligence: Latin America
  res: 2
  pop: 0
  muster: 1
Dakar:
  type: Land
  alligence: French North Africa
  res: 0
  pop: 0
  muster: 0
Morocco:
  type: Land
  alligence: French North Africa
  res: 0
  pop: 0
  muster: 0
Algiers:
  type: Land
  alligence: French North Africa
  res: 0
  pop: 1
  muster: 2
Tunisia:
  type: Land
  alligence: French North Africa
  res: 0
  pop: 0
  muster: 0
Sfax:
  type: Land
  alligence: French North Africa
  res: 0
  pop: 0
  muster: 0
Gibraltar:
  type: Strait
  alligence: Gibraltar
  res: 0
  pop: 0
  muster: 1
Madeira Sea:
  type: Sea
Lisbon:
  type: Land
  alligence: Portugal
  res: 1
  pop: 0
  muster: 1
Madrid:
  type: Land
  alligence: Spain
  res: 0
  pop: 1
  muster: 3
Leon:
  type: Land
  alligence: Spain
  res: 0
  pop: 0
  muster: 0
Barcelona:
  type: Land
  alligence: Spain
  res: 0
  pop: 1
  muster: 0
Azores:
  type: Strait
  alligence: Portugal
  res: 0
  pop: 0
  muster: 0
Bay of Biscay:
  type: Sea
Dublin:
  type: Land
  alligence: Ireland
  res: 0
  pop: 0
  muster: 1
Irminger Sea:
  type: Sea
Iceland:
  type: Land
  alligence: Denmark
  res: 0
  pop: 0
  muster: 0
Greenland Sea:
  type: Sea
Norwegian Sea:
  type: Sea
Nordkapp Sea:
  type: Sea
North Sea:
  type: Sea
English Channel:
  type: Sea
Glasgow:
  type: Land
  alligence: Britain
  res: 1
  pop: 1
  muster: 2
London:
  type: Land
  alligence: Britain
  res: 1
  pop: 3
  muster: 3
Paris:
  type: Land
  alligence: France
  res: 0
  pop: 2
  muster: 3
Lorraine:
  type: Land
  alligence: France
  res: 2
  pop: 0
  muster: 0
Gascony:
  type: Land
  alligence: France
  res: 0
  pop: 0
  muster: 0
Marseille:
  type: Land
  alligence: France
  res: 0
  pop: 1
  muster: 2
Western Mediterranean:
  type: Sea
Sardinia:
  type: Land
  alligence: Italy
  res: 0
  pop: 0
  muster: 0
Tyrrhenian Sea:
  type: Sea
Malta:
  type: Strait
  alligence: Malta
  res: 0
  pop: 0
  muster: 1
Sicily:
  type: Strait
  alligence: Italy
  res: 0
  pop: 0
  muster: 0
Central Mediterranean:
  type: Sea
Adriatic Sea:
  type: Sea
Milan:
  type: Land
  alligence: Italy
  res: 1
  pop: 1
  muster: 2
Rome:
  type: Land
  alligence: Italy
  res: 0
  pop: 2
  muster: 3
Venice:
  type: Land
  alligence: Italy
  res: 1
  pop: 0
  muster: 0
Taranto:
  type: Land
  alligence: Italy
  res: 0
  pop: 0
  muster: 0
Tripoli:
  type: Land
  alligence: Libya
  res: 0
  pop: 1
  muster: 2
Cyrenaica:
  type: Land
  alligence: Libya
  res: 0
  pop: 0
  muster: 0
Amsterdam:
  type: Land
  alligence: Low Countries
  res: 0
  pop: 1
  muster: 2
Vienna:
  type: Land
  alligence: Austria
  res: 0
  pop: 1
  muster: 2
Munich:
  type: Land
  alligence: Germany
  res: 0
  pop: 1
  muster: 2
Ruhr:
  type: Land
  alligence: Germany
  res: 3
  pop: 2
  muster: 3
Berlin:
  type: Land
  alligence: Germany
  res: 1
  pop: 3
  muster: 3
Copenhagen:
  type: Strait
  alligence: Denmark
  res: 1
  pop: 0
  muster: 1
Oslo:
  type: Land
  alligence: Norway
  res: 1
  pop: 0
  muster: 1
Narvik:
  type: Land
  alligence: Norway
  res: 0
  pop: 0
  muster: 0
Gallivare:
  type: Land
  alligence: Sweden
  res: 1
  pop: 0
  muster: 0
Stockholm:
  type: Land
  alligence: Sweden
  res: 1
  pop: 1
  muster: 2
Petsamo:
  type: Land
  alligence: Finland
  res: 1
  pop: 0
  muster: 0
Helsinki:
  type: Land
  alligence: Finland
  res: 0
  pop: 0
  muster: 1
Barents Sea:
  type: Sea
White Sea:
  type: Sea
Gulf of Bothnia:
  type: Sea
Baltic Sea:
  type: Sea
Riga:
  type: Land
  alligence: Baltic States
  res: 0
  pop: 0
  muster: 1
Konigsberg:
  type: Land
  alligence: Germany
  res: 0
  pop: 1
  muster: 2
Warsaw:
  type: Land
  alligence: Poland
  res: 1
  pop: 1
  muster: 3
Vilna:
  type: Land
  alligence: Poland
  res: 0
  pop: 0
  muster: 1
Lvov:
  type: Land
  alligence: Poland
  res: 0
  pop: 1
  muster: 2
Prague:
  type: Land
  alligence: Czechoslovakia
  res: 0
  pop: 1
  muster: 2
Budapest:
  type: Land
  alligence: Hungary
  res: 1
  pop: 1
  muster: 2
Croatia:
  type: Land
  alligence: Yugoslavia
  res: 1
  pop: 0
  muster: 0
Belgrade:
  type: Land
  alligence: Yugoslavia
  res: 0
  pop: 0
  muster: 1
Albania:
  type: Land
  alligence: Albania
  res: 0
  pop: 0
  muster: 0
Athens:
  type: Land
  alligence: Greece
  res: 1
  pop: 0
  muster: 1
Bucharest:
  type: Land
  alligence: Rumania
  res: 2
  pop: 1
  muster: 2
Sofia:
  type: Land
  alligence: Bulgaria
  res: 1
  pop: 0
  muster: 1
Aegean Sea:
  type: Sea
Crete:
  type: Sea
Eastern Mediterranean:
  type: Sea
Egypt:
  type: Land
  alligence: Middle East
  res: 0
  pop: 0
  muster: 0
Suez:
  type: Strait
  alligence: Middle East
  res: 0
  pop: 1
  muster: 2
Sudan:
  type: Land
  alligence: Middle East
  res: 0
  pop: 0
  muster: 0
Jordan:
  type: Land
  alligence: Middle East
  res: 0
  pop: 0
  muster: 0
Iraq:
  type: Land
  alligence: Middle East
  res: 1
  res_afr: 1
  pop: 0
  muster: 0
Damascus:
  type: Land
  alligence: Syria
  res: 0
  pop: 0
  muster: 1
Red Sea:
  type: Sea
Gulf of Aden:
  type: Sea
West Indian Ocean:
  type: Sea
East Indian Ocean:
  type: Sea
Arabian Sea:
  type: Sea
Persian Gulf:
  type: Sea
Bombay:
  type: Land
  alligence: India
  res: 1
  res_afr: 1
  pop: 1
  muster: 2
Karachi:
  type: Land
  alligence: India
  res: 0
  res_afr: 0
  pop: 0
  muster: 0
Delhi:
  type: Land
  alligence: India
  res: 1
  res_afr: 1
  pop: 2
  muster: 3
Kabul:
  type: Land
  alligence: Afghanistan
  res: 0
  pop: 0
  muster: 1
Shiraz:
  type: Land
  alligence: Persia
  res: 0
  pop: 0
  muster: 0
Tehran:
  type: Land
  alligence: Persia
  res: 0
  pop: 1
  muster: 2
Abadan:
  type: Land
  alligence: Persia
  res: 2
  res_afr: 2
  pop: 0
  muster: 0
Tabriz:
  type: Land
  alligence: Persia
  res: 0
  pop: 0
  muster: 0
Kars:
  type: Land
  alligence: Turkey
  res: 0
  pop: 0
  muster: 0
Sinope:
  type: Land
  alligence: Turkey
  res: 0
  pop: 0
  muster: 0
Adana:
  type: Land
  alligence: Turkey
  res: 0
  pop: 0
  muster: 0
Ankara:
  type: Land
  alligence: Turkey
  res: 0
  pop: 1
  muster: 3
Izmir:
  type: Land
  alligence: Turkey
  res: 1
  pop: 0
  muster: 1
Istanbul:
  type: Strait
  alligence: Turkey
  res: 0
  pop: 1
  muster: 2
Southern Caspian Sea:
  type: Sea
Northern Caspian Sea:
  type: Sea
Eastern Black Sea:
  type: Sea
Western Black Sea:
  type: Sea
Sea of Azov:
  type: Sea
Archangel:
  type: Land
  alligence: USSR
  res: 0
  pop: 0
  muster: 0
Vologda:
  type: Land
  alligence: USSR
  res: 0
  pop: 0
  muster: 0
Gorky:
  type: Land
  alligence: USSR
  res: 0
  pop: 0
  muster: 0
Perm:
  type: Land
  alligence: USSR
  res: 0
  pop: 0
  muster: 0
Urals:
  type: Land
  alligence: USSR
  res: 1
  pop: 1
  muster: 2
Western Siberia:
  type: Land
  alligence: USSR
  res: 1
  pop: 0
  muster: 0
Leningrad:
  type: Land
  alligence: USSR
  res: 0
  pop: 2
  muster: 3
Moscow:
  type: Land
  alligence: USSR
  res: 0
  pop: 3
  muster: 3
Murmansk:
  type: Land
  alligence: USSR
  res: 0
  pop: 0
  muster: 0
Penza:
  type: Land
  alligence: USSR
  res: 0
  pop: 0
  muster: 0
Ufa:
  type: Land
  alligence: USSR
  res: 1
  pop: 0
  muster: 0
Kazakhstan:
  type: Land
  alligence: USSR
  res: 0
  pop: 0
  muster: 0
Belorussia:
  type: Land
  alligence: USSR
  res: 0
  pop: 0
  muster: 0
Bryansk:
  type: Land
  alligence: USSR
  res: 0
  pop: 0
  muster: 0
Voronezh:
  type: Land
  alligence: USSR
  res: 0
  pop: 0
  muster: 0
Stalingrad:
  type: Land
  alligence: USSR
  res: 0
  pop: 1
  muster: 2
Grozny:
  type: Land
  alligence: USSR
  res: 0
  pop: 0
  muster: 0
Turkmenistan:
  type: Land
  alligence: USSR
  res: 0
  pop: 0
  muster: 0
Kuban:
  type: Land
  alligence: USSR
  res: 0
  pop: 0
  muster: 0
Georgia:
  type: Land
  alligence: USSR
  res: 0
  pop: 0
  muster: 0
Baku:
  type: Land
  alligence: USSR
  res: 3
  res_afr: 1
  pop: 2
  muster: 3
Kiev:
  type: Land
  alligence: USSR
  res: 1
  pop: 1
  muster: 2
Kharkov:
  type: Land
  alligence: USSR
  res: 1
  pop: 1
  muster: 2
Odessa:
  type: Land
  alligence: USSR
  res: 2
  pop: 1
  muster: 2
Sevastopol:
  type: Strait
  alligence: USSR
  res: 0
  pop: 0
  muster: 0