Canada: 
  capital: Ottawa
  x: 271 
  y: 503
USA: 
  capital: Washington
  x: 109 
  y: 654
Latin America: 
  capital: Latin America
  x: 151 
  y: 1914
French North Africa: 
  capital: Algiers
  x: 866 
  y: 1849
Gibraltar: 
  capital: Gibraltar
  x: 537 
  y: 1734
Portugal: 
  capital: Lisbon
  x: 457 
  y: 1617
Spain: 
  capital: Madrid
  x: 766 
  y: 1514
Ireland: 
  capital: Dublin
  x: 626 
  y: 754
Denmark: 
  capital: Copenhagen
  x: 1243 
  y: 771
Britain: 
  capital: London
  x: 860 
  y: 854
France: 
  capital: Paris
  x: 907 
  y: 1232
Italy: 
  capital: Rome
  x: 1371 
  y: 1497
Malta: 
  capital: Malta
  x: 1276 
  y: 1813
Libya: 
  capital: Tripoli
  x: 1520 
  y: 2014
Low Countries: 
  capital: Amsterdam
  x: 1109 
  y: 886
Austria: 
  capital: Vienna
  x: 1323 
  y: 1203
Germany: 
  capital: Berlin
  x: 1254 
  y: 989
Norway: 
  capital: Oslo
  x: 1314 
  y: 397
Sweden: 
  capital: Stockholm
  x: 1443 
  y: 400
Finland: 
  capital: Helsinki
  x: 1760 
  y: 283
Baltic States: 
  capital: Riga
  x: 1717 
  y: 723
Poland: 
  capital: Warsaw
  x: 1663 
  y: 911
Czechoslovakia: 
  capital: Prague
  x: 1420 
  y: 1060
Hungary: 
  capital: Budapest
  x: 1546 
  y: 1214
Yugoslavia: 
  capital: Belgrade
  x: 1614 
  y: 1311
Albania: 
  capital: Albania
  x: 1617 
  y: 1497
Greece: 
  capital: Athens
  x: 1729 
  y: 1569
Rumania: 
  capital: Bucharest
  x: 1920 
  y: 1251
Bulgaria: 
  capital: Sofia
  x: 1860 
  y: 1406
Middle East: 
  capital: Suez
  x: 2386 
  y: 1877
Syria: 
  capital: Damascus
  x: 2409 
  y: 1729
India: 
  capital: Delhi
  x: 3303 
  y: 1477
Afghanistan: 
  capital: Kabul
  x: 2734 
  y: 1663
Persia: 
  capital: Tehran
  x: 2943 
  y: 1489
Turkey: 
  capital: Ankara
  x: 2266 
  y: 1366
USSR: 
  capital: Moscow
  x: 2123 
  y: 611
