Canada: Ottawa
USA: Washington
Latin America: Rio de Janeiro
French North Africa: Algiers
Gibraltar: Gibraltar
Portugal: Lisbon
Spain: Madrid
Ireland: Dublin
Denmark: Copenhagen
Britain: London
France: Paris
Italy: Rome
Malta: Malta
Libya: Tripoli
Low Countries: Amsterdam
Austria: Vienna
Germany: Berlin
Norway: Oslo
Sweden: Stockholm
Finland: Helsinki
Baltic States: Riga
Poland: Warsaw
Czechoslovakia: Prague
Hungary: Budapest
Yugoslavia: Belgrade
Albania: Albania
Greece: Athens
Rumania: Bucharest
Bulgaria: Sofia
Middle East: Suez
Syria: Damascus
India: Delhi
Afghanistan: Kabul
Persia: Tehran
Turkey: Ankara
USSR: Moscow
