Afghanistan:
  capital: Kabul
  x: 3134
  y: 1517
Albania:
  capital: Albania
  x: 1617
  y: 1497
Austria:
  capital: Vienna
  x: 1323
  y: 1203
Baltic States:
  capital: Riga
  x: 1717
  y: 723
Britain:
  capital: London
  x: 860
  y: 804
Bulgaria:
  capital: Sofia
  x: 1860
  y: 1406
Canada:
  capital: Ottawa
  x: 271
  y: 503
Czechoslovakia:
  capital: Prague
  x: 1420
  y: 1060
Denmark:
  capital: Copenhagen
  x: 1243
  y: 771
Finland:
  capital: Helsinki
  x: 1760
  y: 283
France:
  capital: Paris
  x: 907
  y: 1232
French North Africa:
  capital: Algiers
  x: 866
  y: 1849
Germany:
  capital: Berlin
  x: 1254
  y: 989
Gibraltar:
  capital: Gibraltar
  x: 537
  y: 1734
Greece:
  capital: Athens
  x: 1729
  y: 1569
Hungary:
  capital: Budapest
  x: 1546
  y: 1214
India:
  capital: Delhi
  x: 3303
  y: 1477
Ireland:
  capital: Dublin
  x: 626
  y: 754
Italy:
  capital: Rome
  x: 1371
  y: 1497
Latin America:
  capital: Latin America
  x: 151
  y: 1914
Libya:
  capital: Tripoli
  x: 1520
  y: 2014
Low Countries:
  capital: Amsterdam
  x: 1109
  y: 886
Malta:
  capital: Malta
  x: 1276
  y: 1813
Middle East:
  capital: Suez
  x: 2386
  y: 1877
Norway:
  capital: Oslo
  x: 1314
  y: 397
Portugal:
  capital: Lisbon
  x: 457
  y: 1617
Spain:
  capital: Madrid
  x: 766
  y: 1514
Sweden:
  capital: Stockholm
  x: 1443
  y: 400
USA:
  capital: Washington
  x: 109
  y: 654
Persia:
  capital: Tehran
  x: 2943
  y: 1489
Poland:
  capital: Warsaw
  x: 1663
  y: 911
Rumania:
  capital: Bucharest
  x: 1920
  y: 1251
Syria:
  capital: Damascus
  x: 2409
  y: 1729
Turkey:
  capital: Ankara
  x: 2266
  y: 1366
USSR:
  capital: Moscow
  x: 2123
  y: 611
Yugoslavia:
  capital: Belgrade
  x: 1614
  y: 1311
